import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter } from "next/font/google";
import "./globals.css";
import { Navbar } from "../components/navbar";
import { ClerkProvider } from "@clerk/nextjs";
import Provider from "./provider";

import { Toaster } from "@/components/ui/sonner";
import { Analytics } from "@vercel/analytics/react";
import RootProviders from "./provider";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "EduScale",
  description: "A Modern Education Management Platform",
  openGraph: {
    images: [
      "https://utfs.io/f/59a2a3e1-f1b9-4152-97d2-38dea6e14106-3hq5f6.png",
    ],
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <html
        lang="en"
        suppressHydrationWarning
        className="dark"
        style={{
          colorScheme: "dark",
        }}
      >
        <body className={inter.className}>
          <Toaster />
          <RootProviders>{children}</RootProviders>

          <Analytics />
        </body>
      </html>
    </ClerkProvider>
  );
}
